blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'       # 命名空间

urlpatterns = [
    # prefix url --> xxx/
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('categories/<int:pk>/', views.category, name='category'),
    path('tags/<int:pk>/', views.tag, name='tag'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

# prefix url --> xxx/
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.html import strip_tags    # 去除html标签
import markdown


class Category(models.Model):
    """
    分类
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章
    """
    # 文章标题，小文本
    title = models.CharField(max_length=70)

    # 文章正文，大文本，用TextField
    body = models.TextField()

    # 文章创建时间和最后一次修改时间
    created_time = models.DateTimeField(default=timezone.now)   # default没填写时的默认值，可以为常量，可以为可调用对象(timezone.now)
                                                                # timezone.now()会在创建时直接产生，可能与保存到数据库中时的值产生时差
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，blank=True
    excerpt = models.CharField(max_length=200, blank=True)

    # 分类与标签
    # 分类，一对多，级联删除
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # 标签，多对多，可以为空
    tags = models.ManyToManyField(Tag, blank=True)

    # 作者，一对多，使用内置User类，级联删除
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # Meta内部类，通过指定属性的值为Post对象添加默认特性
    class Meta:
        ordering = ['-created_time']    # 默认按照创建时间倒序

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """复写save方法，自动更新修改时间"""
        self.modified_time = timezone.now()

        # 自动生成摘要 -->
        # 1.先markdown转换成html；
        # 2.去掉html标签；
        # 3.提取前N个字符作为摘要。
        md = markdown.Markdown(extensions=[     # 不需要用到toc文章目录扩展
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.excerpt = strip_tags(md.convert(self.body))[:54]   # N为54

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """返回当前post的detail的url地址"""
        return reverse('blog:detail', kwargs={'pk': self.pk})

comments/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils.text import slugify
from .models import Post, Category, Tag
import markdown
from markdown.extensions.toc import TocExtension


def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/index.html', context={
        'post_list': post_list,
    })


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',  # 基础扩展
        'markdown.extensions.codehilite',  # 代码高亮扩展
        # 'markdown.extensions.fenced_code',
        # 'markdown.extensions.toc',  # 自动生成目录
        TocExtension(slugify=slugify)  # 代替toc，处理markdown无法处理的锚点问题(#_1, #_3)
    ])
    post.body = md.convert(post.body)  # markdown转换成html
    post.toc = md.toc  # 动态添加post的toc属性，也是转换成的html
    return render(request, 'blog/detail.html', context={'post': post, })


def archive(request, year, month):
    """归档视图函数"""
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', context={
        'post_list': post_list,
    })


def category(request, pk):
    """分类视图函数"""
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/index.html', context={
        'post_list': post_list
    })


def tag(request, pk):
    """标签视图函数"""
    t = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=t).order_by('-created_time')
    return render(request, 'blog/index.html', context={
        'post_list': post_list
    })

comments/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{#{% label %} 模板标签#}
{% load static %}
{% load blog_extras %}  {# 导入自定义模板标签 #}
<!DOCTYPE html>
<html>
<head>
    <title>我的博客demo</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

    <!-- 代码高亮 -->
    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>

</head>

<body>

<!-- 顶部导航 -->
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>我的博客demo</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
{#                搜索框#}
{#                <div id="header-search-box">#}
{#                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>#}
{#                    <div id="search-form" class="search-form">#}
{#                        <form role="search" method="get" id="searchform" action="#">#}
{#                            <input type="search" placeholder="搜索" required>#}
{#                            <button type="submit"><span class="ion-ios-search-strong"></span></button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<!-- 博客主体 -->
<div class="content-body">
    <div class="container">
        <div class="row">

            <!-- 文章 -->
            <main class="col-md-8">
                {% block main %}<!-- 占位 -->
                {% endblock main %}
            </main>

            <!-- 目录 -->
            <aside class="col-md-4">
                {% block toc %}<!-- 占位 -->
                {% endblock toc %}
            </aside>

            <!-- 相关归档 -->
            <aside class="col-md-4">
                {% show_recent_posts %}<!-- 展示最近文章 -->

                {% show_archives %}<!-- 归档 -->

                {% show_categories %}<!-- 分类 -->

                {% show_tags %}<!-- 标签云 -->
            </aside>
        </div>
    </div>
</div>

<!-- 底部版权 -->
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2020- <a href="#" title="回到顶部">回到顶部</a></p>
            </div>
        </div>
    </div>
</footer>

<!-- 移动端适配菜单 -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="{% url 'blog:index' %}">博客</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static '/blog/js/script.js' %}"></script>
<!-- 代码高亮js -->
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <!-- 文章部分 -->
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">** 评论</a></span>
                <span class="views-count"><a href="#">** 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}<!-- 通过safe过滤器，不需要对获得的html进行转义 -->
        </div>
    </article>

    <!-- 评论部分 -->
    {#    <section class="comment-area" id="comment-area">#}
    {#        <hr>#}
    {#        <h3>发表评论</h3>#}
    {#        <form action="#" method="post" class="comment-form">#}
    {#            <div class="row">#}
    {#                <div class="col-md-4">#}
    {#                    <label for="id_name">名字：</label>#}
    {#                    <input type="text" id="id_name" name="name" required>#}
    {#                </div>#}
    {#                <div class="col-md-4">#}
    {#                    <label for="id_email">邮箱：</label>#}
    {#                    <input type="email" id="id_email" name="email" required>#}
    {#                </div>#}
    {#                <div class="col-md-4">#}
    {#                    <label for="id_url">网址：</label>#}
    {#                    <input type="text" id="id_url" name="url">#}
    {#                </div>#}
    {#                <div class="col-md-12">#}
    {#                    <label for="id_comment">评论：</label>#}
    {#                    <textarea name="comment" id="id_comment" required></textarea>#}
    {#                    <button type="submit" class="comment-btn">发表</button>#}
    {#                </div>#}
    {#            </div>    <!-- row -->#}
    {#        </form>#}
    {#        <div class="comment-list-panel">#}
    {#            <h3>评论列表，共 <span>4</span> 条评论</h3>#}
    {#            <ul class="comment-list list-unstyled">#}
    {#                <li class="comment-item">#}
    {#                    <span class="nickname">追梦人物</span>#}
    {#                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月12日 14:56</time>#}
    {#                    <div class="text">#}
    {#                        文章观点又有道理又符合人性，这才是真正为了表达观点而写，不是为了迎合某某知名人士粉丝而写。我觉得如果琼瑶是前妻，生了三孩子后被一不知名的女人挖了墙角，我不信谁会说那个女人是追求真爱，说同情琼瑶骂小三的女人都是弱者。#}
    {#                    </div>#}
    {#                </li>#}
    {#                <li class="comment-item">#}
    {#                    <span class="nickname">zmrenwu</span>#}
    {#                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月11日 23:56</time>#}
    {#                    <div class="text">#}
    {#                        本能有可能会冲破格局，但格局有时候也会拘住本能。#}
    {#                    </div>#}
    {#                </li>#}
    {#                <li class="comment-item">#}
    {#                    <span class="nickname">蝙蝠侠</span>#}
    {#                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月9日 8:56</time>#}
    {#                    <div class="text">#}
    {#                        其实真理一般是属于沉默的大多数的。那些偏激的观点只能吸引那些同样偏激的人。前几年琼瑶告于妈抄袭，大家都表示大快人心，说明吃瓜观众都只是就事论事，并不是对琼瑶有偏见。#}
    {#                    </div>#}
    {#                </li>#}
    {#                <li class="comment-item">#}
    {#                    <span class="nickname">长江七号</span>#}
    {#                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年2月12日 12:56</time>#}
    {#                    <div class="text">#}
    {#                        观点我很喜欢！就是哎嘛本来一清二楚的，来个小三小四乱七八糟一团乱麻夹缠不清，简直麻烦要死#}
    {#                    </div>#}
    {#                </li>#}
    {#            </ul>#}
    {#        </div>#}
    {#    </section>#}
{% endblock main %}

<!-- 右侧文章目录部分 -->
{% block toc %}
    <div class="widget widget-content">
    <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title widget-title">文章目录</h3>
            </div>
            <div class="panel-body">
                {{ post.toc|safe }}
            </div>
        </div>
    </div>

{% endblock toc %}

templates/blog/inclusions/_archives.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title widget-title">归档</h3>
    </div>
    <div class="panel-body">
        <div class="widget widget-archives">
            <ul>
                {% for date in date_list %}
                    <li>
                        <a href="{% url 'blog:archive' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
                    </li>
                {% empty %}
                    暂无归档
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/blog/inclusions/_categories.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title widget-title">分类</h3>
    </div>
    <div class="panel-body">
        <div class="widget widget-category">
            <ul>
                {% for category in category_list %}
                    <li>
                        <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count"
                                                                                                  (13)></span> </a>
                    </li>
                {% empty %}
                    暂无分类
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title widget-title">最新文章</h3>
    </div>
    <div class="panel-body">
        <div class="widget widget-recent-posts">
            <ul>
                {% for post in recent_post_list %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% empty %}
                    暂无文章
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/blog/inclusions/_tags.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title widget-title">标签云</h3>
    </div>
    <div class="panel-body">
        <div class="widget widget-tag-cloud">
            <ul>
                {% for tag in tag_list %}
                    <li>
                        <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                    </li>
                {% empty %}
                    暂无标签
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    <!-- 条目 -->
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <!-- 文章标题 -->
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                                <span class="comments-link"><a href="#">** 评论</a></span>
                                <span class="views-count"><a href="#">** 阅读</a></span>
                            </div>
                        </header>
                    </h3>
                </div>
                <div class="panel-body">
                    <!-- 文章预览 -->
                    <div class="entry-content clearfix">
                        {{ post.excerpt }}...
                    </div>
                </div>


        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章</div>
    {% endfor %}

    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <!-- 分页
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
    -->
{% endblock main %}

templates/mybase.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>我的博客demo</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<!-- 顶部导航 -->
<div class="navbar navbar-inverse navbar-fixed-top", role="navigation", id="menu-nav">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">切换导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">我的博客demo</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">综述</a></li>
                <li class="active"><a href="#">综述</a></li>
                <li class="active"><a href="#">综述</a></li>
            </ul>
        </div>
    </div>
</div>


<h1>你好，世界！</h1>

<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</body>
</html>